Foundation_English = float(input("your score in Foundation English "))
General_Business = float(input("your score in General Business "))
Introduction_to_Computer_Systems = float(input("your score in Introduction to Computer Systems "))
Computer_Programming = float(input("your score in Computer Programming "))

print("----- Your Score -----")
print("Foundation English :",Foundation_English)
print("General Business :",General_Business)
print("Introduction to Computer Systems :",Introduction_to_Computer_Systems)
print("Computer Programming :",Computer_Programming)